### ISSUE TITLE
setting up with event-node + tron-gird fails

### ISSUE THREAD

**Issue by the-tchaw** [TRON-US/tron-cli#16]
Hello I just installed tron-cli tried to start a node with tron-grid got the below error (note i created a database, user and pass)

I think the problem is with cloning `https://github.com/tronprotocol/java-tron.git` branch `event_parser` as you note in the logs below it could not found the branch. and upon inspection of the git repo indeed no branch named `event_parser` exists there.

Please help me resolve this

```
$ tron-cli i
[ TRON-CLI ]: Switched to <Interactive Mode>...

 _________  ____  _  __    _______   ____
/_  __/ _ \/ __ \/ |/ /___/ ___/ /  /  _/
 / / / , _/ /_/ /    /___/ /__/ /___/ /  
/_/ /_/|_|\____/_/|_/    \___/____/___/  

[ I-MODE ]: Welcome to use troncli interactive mode!
[ I-MODE ]: If you already initialized and fetched code, you can skip this(init) step by enter [skip], otherwise press any key to continue.

[ I-MODE ]: Use latest supported version[3.5.0.1] of java-tron? ([y]/n)
Y
    Y
[ I-MODE ]: Reset everything? (y/[n]))
y
[ TRON-CLI ]: Creating folders...
[ TRON-CLI ]: Shutting down node(s)...
✓ : process: 91822 is shut down
kill: (91822): No such process
✓ : Folders reset.
✓ : Folders are created:
    <path>/ 
    └──/tron_nodes
        ├──/fullnode
        ├──/soliditynode
        ├──/eventnode
        └──/gridapi
[ TRON-CLI ]: Downloading full-node jar from released build...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:10<00:00,  9.34it/s]
✓ : .jar file of Fullnode is successfully downloaded
[ TRON-CLI ]: Downloading solidity-node jar from released build...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:12<00:00,  7.74it/s]
✓ : .jar file of Soliditynode is successfully downloaded
[ TRON-CLI ]: Git cloning https://github.com/tronprotocol/java-tron.git-branch: event_parser...
Cloning into '<path>/tron_nodes/eventnode'...
warning: Could not find remote branch event_parser to clone.
fatal: Remote branch event_parser not found in upstream origin
✓ : event-node source code cloned
[ TRON-CLI ]: Git cloning https://github.com/tronprotocol/tron-grid.git-branch: dev...
Cloning into '<path>/tron_nodes/gridapi'...
warning: Could not find remote branch dev to clone.
fatal: Remote branch dev not found in upstream origin
✓ : tron-grid source code cloned
✓ : full node jar move to:
    <path>/tron_nodes/fullnode/full.jar
✓ : solidity node jar move to:
    <path>/tron_nodes/soliditynode/solidity.jar
✓ : initialization finished
[ I-MODE ]: Setting up a private testnet or sync to mainnet? ([private]/main)
private
    private
[ I-MODE ]: Do you want set up event services (event-node + tron-gird)? (y/[n]))
y
[ I-MODE ]: !!! NOTICE: Assume you already installed MongoDB and created user with a role.
[ I-MODE ]: Enter your db name:
tron-test
[ I-MODE ]: Enter your db user-name:
tron-test
[ I-MODE ]: Enter your db user-password:
<pass>
[ TRON-CLI ]: Setting up config files...
✓ : config initialized
✓ : net type set to: 
    private
✓ : full-node http request set to listen: 
    127.0.0.1:8500
✓ : solidity-node request set to listen: 
    127.0.0.1:8600
✓ : event-node request set to listen: 
    127.0.0.1:8400
✓ : full-node rpc request set to listen: 
    127.0.0.1:58500
✓ : solidity-node rpc request set to listen: 
    127.0.0.1:58600
✓ : event-node rpc request set to listen: 
    127.0.0.1:58400
✓ : enable in memory db:
    True
✓ : db sync mode set to: 
    asynchronous
✓ : save history transaction: 
    disabled
✓ : save internal transaction: 
    disabled
✓ : db settings stored
Traceback (most recent call last):
  File "<path>/venv/bin/tron-cli", line 5, in <module>
    troncli.cli.main()
  File "<path>/venv/lib/python3.10/site-packages/troncli/cli.py", line 281, in main
    cbox.main([init, config, run, stop, status, quick, log, version, i])
  File "<path>/venv/lib/python3.10/site-packages/cbox/cli.py", line 117, in main
    exitcode = executor(func, argv, input_stream, output_stream, error_stream)
  File "<path>/venv/lib/python3.10/site-packages/cbox/executors.py", line 50, in _execute_multi_cmd
    return funcs_dict[subcmd](**func_kwargs)
  File "<path>/venv/lib/python3.10/site-packages/cbox/cli.py", line 79, in wrapper
    return f(*args, **kwargs)
  File "<path>/venv/lib/python3.10/site-packages/troncli/cli.py", line 260, in i
    config(choose_your_poison['nettype'], 0, 0, 0, 0, 0, 0, '', '', '', '', 0,
  File "<path>/venv/lib/python3.10/site-packages/cbox/cli.py", line 79, in wrapper
    return f(*args, **kwargs)
  File "<path>/venv/lib/python3.10/site-packages/troncli/cli.py", line 96, in config
    loop.run_until_complete(config_handler.store_db_settings(dbname, dbusername, dbpassword, gridport))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "<path>/venv/lib/python3.10/site-packages/troncli/h_config.py", line 302, in store_db_settings
    await self.change_eventnode_db_settings()
  File "<path>/venv/lib/python3.10/site-packages/troncli/h_config.py", line 318, in change_eventnode_db_settings
    self.phrase.store_json2javabeanconfig_to_file(self.eventnode_db_properties, _target_file_path_sol)
  File "<path>/venv/lib/python3.10/site-packages/troncli/utils.py", line 366, in store_json2javabeanconfig_to_file
    f = open(target_file_path, 'w')
FileNotFoundError: [Errno 2] No such file or directory: '<path>/tron_nodes/eventnode/src/main/resources/mongodb.properties'
```

**Comment by the-tchaw** [comment]
Actually there is 2 cloning that failed:

- https://github.com/tronprotocol/java-tron.git-branch: event_parser
- https://github.com/tronprotocol/tron-grid.git-branch: dev P.S. this repo is deprecated

```
[ TRON-CLI ]: Git cloning https://github.com/tronprotocol/java-tron.git-branch: event_parser...
Cloning into '<path>/tron_nodes/eventnode'...
warning: Could not find remote branch event_parser to clone.
fatal: Remote branch event_parser not found in upstream origin
✓ : event-node source code cloned
[ TRON-CLI ]: Git cloning https://github.com/tronprotocol/tron-grid.git-branch: dev...
Cloning into '<path>/tron_nodes/gridapi'...
warning: Could not find remote branch dev to clone.
fatal: Remote branch dev not found in upstream origin
✓ : tron-grid source code cloned
```
